version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    networks:
      - dhis
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
    - /root/dhis2_home/dhisdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  web:
    image: dhis2/core:2.33.0
    volumes:
    - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    environment:
    - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    networks:
      - dhis
    ports:
    - "8082:8080"
    depends_on:
    - db
    
networks:
  dhis:
    driver: bridge
